version: 0.0
os: linux
files:
    - source: /
      destination: /home/ec2-user/api
hooks:
    BeforeInstall:
        - location: scripts/before-install.sh
          timeout: 1200
          runas: ec2-user
    AfterInstall:
        - location: scripts/after-install.sh
          timeout: 1200
          runas: ec2-user
    ApplicationStart:
        - location: scripts/start.sh
          timeout: 60
          runas: ec2-user
